GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/26

###
POST  http://localhost:3000/subscribers
Content-Type: application/json
 {
     
 "name" :"Amazing Person",
 "subscribedToChannel":"web Dev Simplified"

    
    


}

